const products=[
 {id:1,name:'Country Eggs',unit:'6 pieces',price:72,old:84,emoji:'🥚',category:'Dairy & eggs',tag:'BESTSELLER'},
 {id:2,name:'Ooty Carrots',unit:'500 g',price:49,old:60,emoji:'🥕',category:'Fresh vegetables',tag:'17% OFF'},
 {id:3,name:'A2 Desi Cow Milk',unit:'500 ml',price:38,emoji:'🥛',category:'Dairy & eggs'},
 {id:4,name:'Premium Ponni Rice',unit:'5 kg',price:349,old:399,emoji:'🍚',category:'Pantry',tag:'SAVE ₹50'},
 {id:5,name:'Nendran Banana',unit:'500 g',price:45,emoji:'🍌',category:'Fresh fruits'},
 {id:6,name:'Cold Pressed Gingelly Oil',unit:'1 litre',price:279,emoji:'🫗',category:'Pantry'},
 {id:7,name:'Coorg Filter Coffee',unit:'250 g',price:185,emoji:'☕',category:'Beverages'},
 {id:8,name:'Moringa Leaf Powder',unit:'100 g',price:99,emoji:'🌿',category:'Pantry',tag:'NEW'}
];
const categories=[['Fresh fruits','🍊'],['Fresh vegetables','🥬'],['Dairy & eggs','🥛'],['Pantry','🫘'],['Snacks','🍘'],['Home & care','🧼']];
let active='All';let cart=JSON.parse(localStorage.getItem('marutham-cart')||'{}');
const $=s=>document.querySelector(s),money=n=>`₹${n.toLocaleString('en-IN')}`;
function renderCategories(){ $('#categories').innerHTML=categories.map(([name,emoji])=>`<button class="category" data-category="${name}"><span class="emoji">${emoji}</span><span>${name}</span></button>`).join(''); }
function renderFilters(){const choices=['All',...categories.map(x=>x[0])];$('#filters').innerHTML=choices.map(x=>`<button class="${active===x?'active':''}" data-filter="${x}">${x}</button>`).join('')}
function renderProducts(){let q=$('#searchInput').value.toLowerCase();let list=products.filter(p=>(active==='All'||p.category===active)&&p.name.toLowerCase().includes(q));$('#products').innerHTML=list.length?list.map(p=>`<article class="product"><div class="product-image" data-view="${p.id}">${p.emoji}</div>${p.tag?`<span class="tag">${p.tag}</span>`:''}<h3>${p.name}</h3><span class="unit">${p.unit}</span><div class="product-bottom"><span class="price"><b>${money(p.price)}</b>${p.old?`<s>${money(p.old)}</s>`:''}</span><button class="add" data-add="${p.id}">ADD +</button></div></article>`).join(''):`<p>No market finds match “${q}”. Try another search.</p>`}
function add(id){cart[id]=(cart[id]||0)+1;persist();showToast(`${products.find(p=>p.id===id).name} added to basket`)}
function persist(){localStorage.setItem('marutham-cart',JSON.stringify(cart));let items=Object.values(cart).reduce((a,b)=>a+b,0);$('#cartCount').textContent=items;$('#cartSubline').textContent=`${items} item${items===1?'':'s'}`;let total=Object.entries(cart).reduce((sum,[id,n])=>sum+products.find(p=>p.id===+id).price*n,0);$('#cartTotal').textContent=money(total);$('#deliveryNote').textContent=total>=499?'You qualify for free delivery!':'Add '+money(499-total)+' for free delivery';$('#cartItems').innerHTML=items?Object.entries(cart).map(([id,n])=>{let p=products.find(x=>x.id===+id);return `<div class="cart-row"><span class="mini">${p.emoji}</span><div><h3>${p.name}</h3><p>${p.unit} · ${money(p.price)}</p><div class="qty"><button data-change="${id}" data-by="-1">−</button><b>${n}</b><button data-change="${id}" data-by="1">+</button></div></div><button class="remove" data-remove="${id}">Remove</button></div>`}).join(''):`<div class="empty"><div>🧺</div><p>Your basket is waiting for something lovely.</p></div>`}
function openCart(){ $('#cartPanel').classList.add('open');$('#scrim').classList.add('open');$('#cartPanel').setAttribute('aria-hidden','false') }function closeCart(){$('#cartPanel').classList.remove('open');$('#scrim').classList.remove('open');$('#cartPanel').setAttribute('aria-hidden','true')}
function modal(html){$('#modalContent').innerHTML=html;$('#modal').showModal()}
function showToast(text){let t=$('#toast');t.textContent=text;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2600)}
document.addEventListener('click',e=>{let addButton=e.target.closest('[data-add]');if(addButton)add(+addButton.dataset.add);let filter=e.target.closest('[data-filter]');if(filter){active=filter.dataset.filter;renderFilters();renderProducts();$('#shop').scrollIntoView({behavior:'smooth'})}let cat=e.target.closest('[data-category]');if(cat){active=cat.dataset.category;renderFilters();renderProducts();$('#shop').scrollIntoView({behavior:'smooth'})}let view=e.target.closest('[data-view]');if(view){let p=products.find(x=>x.id===+view.dataset.view);modal(`<div style="font-size:92px;text-align:center;background:#edf0e9;padding:20px">${p.emoji}</div><h2>${p.name}</h2><p>${p.unit} · ${money(p.price)}${p.old?` <s>${money(p.old)}</s>`:''}</p><p>Carefully selected and quality checked for your family. Delivered in your preferred time slot.</p><button class="primary" data-modal-add="${p.id}">Add to basket →</button>`)}if(e.target.matches('[data-modal-add]')){add(+e.target.dataset.modalAdd);$('#modal').close()}if(e.target.matches('[data-change]')){let id=e.target.dataset.change;cart[id]+=+e.target.dataset.by;if(cart[id]<=0)delete cart[id];persist()}if(e.target.matches('[data-remove]')){delete cart[e.target.dataset.remove];persist();showToast('Removed from basket')}});
$('#searchInput').addEventListener('input',renderProducts);$('#cartButton').onclick=openCart;$('#closeCart').onclick=closeCart;$('#scrim').onclick=closeCart;$('#modalClose').onclick=()=>$('#modal').close();$('#locationButton').onclick=()=>modal(`<h2>Where should we deliver?</h2><p>Choose a city to see the freshest selection and delivery slots.</p><label for="city">Your city</label><select id="city"><option>Chennai</option><option>Coimbatore</option><option>Madurai</option><option>Tiruchirappalli</option></select><button class="primary" id="saveCity" style="margin-top:18px">Confirm location →</button>`);$('#modal').addEventListener('click',e=>{if(e.target.id==='saveCity'){$('#locationLabel').textContent=$('#city').value;$('#modal').close();showToast('Delivery location updated')}});$('#accountButton').onclick=()=>modal(`<h2>Welcome to Marutham</h2><p>Sign in to save your favourites, track orders, and make every shop a little easier.</p><label>Email address</label><input type="email" placeholder="you@example.com"><button class="primary" style="margin-top:18px">Continue →</button>`);$('#howItWorks').onclick=()=>modal(`<h2>From market to your door</h2><p><b>1. Choose your essentials.</b> Browse fresh produce, pantry staples and local favourites.</p><p><b>2. Pick a slot.</b> Select delivery that fits your day.</p><p><b>3. Unpack the good stuff.</b> Our quality-checked order arrives fresh.</p>`);$('#storyButton').onclick=()=>modal(`<h2>Made for everyday goodness.</h2><p>We started Marutham with a simple belief: buying your groceries should feel considered, not complicated. This demo celebrates the growers and household staples that make Tamil Nadu’s kitchens special.</p>`);$('#checkoutButton').onclick=()=>{if(!Object.keys(cart).length)return showToast('Add a few items before checkout');closeCart();modal(`<h2>Checkout</h2><p>This is a secure demo checkout. Your order total is <b>${$('#cartTotal').textContent}</b>.</p><label>Name</label><input placeholder="Your name"><label>Delivery address</label><input placeholder="House no., street, area"><button class="primary" id="placeOrder" style="margin-top:18px">Place demo order →</button>`)};$('#modal').addEventListener('click',e=>{if(e.target.id==='placeOrder'){cart={};persist();$('#modal').close();showToast('Order placed — your fresh picks are on the way!')}});$('#newsletterForm').onsubmit=e=>{e.preventDefault();e.target.reset();showToast('You’re on the market list!')};document.addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key==='k'){e.preventDefault();$('#searchInput').focus()}if(e.key==='Escape')closeCart()});renderCategories();renderFilters();renderProducts();persist();
